# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\"%\n\x12GetBookByIDRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"N\n\x11\x43reateBookRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05pages\x18\x04 \x01(\x05\"%\n\x10ListBooksRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETBOOKBYIDREQUEST._serialized_start=18
  _GETBOOKBYIDREQUEST._serialized_end=55
  _CREATEBOOKREQUEST._serialized_start=57
  _CREATEBOOKREQUEST._serialized_end=135
  _LISTBOOKSREQUEST._serialized_start=137
  _LISTBOOKSREQUEST._serialized_end=174
# @@protoc_insertion_point(module_scope)
