# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import requests_pb2 as requests__pb2
import responses_pb2 as responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x0erequests.proto\x1a\x0fresponses.proto2\xa8\x01\n\x0c\x42ooksService\x12/\n\x07GetBook\x12\x13.GetBookByIDRequest\x1a\r.BookResponse\"\x00\x12\x34\n\tListBooks\x12\x11.ListBooksRequest\x1a\x12.ListBooksResponse\"\x00\x12\x31\n\nCreateBook\x12\x12.CreateBookRequest\x1a\r.BookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKSSERVICE._serialized_start=51
  _BOOKSSERVICE._serialized_end=219
# @@protoc_insertion_point(module_scope)
